### ISSUE TITLE
Teams Based Scoreboards VS Packet Based

### ISSUE THREAD

**Issue by swqrve** [GleemingKnight/scorey#1]
Teams-based scoreboard APIs can mess with other plugins using teams, like nametag plugins, etc. 
Consider switching to a packet-based approach that won't mess with other plugins.

**Comment by ashtton** [comment]
The way that scorey is implemented, I can assure you that it won't messup other plugins like nametag-api.
Scorey always uses the same instance of a bukkit scoreboard whereas if it changed it, I could see that leading to issues with dependency problems.
